[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    links2004/WebSockets@^2.4.1
    ArduinoJson
    Preferences
    ESPAsyncWebServer

build_src_filter =
    +<**/*.cpp>
    -<led_test.cpp>


[env:led_test]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_src_filter =
    +<led_test.cpp>
    -<main.cpp>
    -<AppGlobals.cpp>
    -<config/*.cpp>
    -<led/*.cpp>
    -<web/*.cpp>
    -<websocket/*.cpp>
    -<gnss/*.cpp>
    -<ntrip/*.cpp>
    -<ble/*.cpp>
    -<logging/*.cpp>